version: '3.1'
# PostgreSQL and pgAdmin4
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: socialsetting
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: jon@dow.com
      PGADMIN_DEFAULT_PASSWORD: postgres
volumes:
  data:
  